### ISSUE TITLE
잘못된 요청입니다. 메세지가 지속적으로 뜨는 현상

### ISSUE THREAD

**Issue by kimhamc** [YJSoft/xe-module-loginxeclient#12]
오늘 LOGIN XE를 통해(서버/클라이언트) 네이버로 로그인이 가능하도록 설치를 해보았습니다.
설치 과정은 https://www.xpressengine.com/tip/22978566 과 http://server.loginxe.cf/ 를 통해 참고하였구요. 레이아웃을 적용한 곳은 http://heycrybaby.com 이며, 로그인 위젯 하단에 반영하는 것까지는 별 무리가 없었습니다. 다만, 링크를 클릭하면 "잘못된 요청입니다"가 확인되며 네이버 로그인 연동이 되질 않습니다. XE공홈에서 찾아봐도 별다른 팁이 보이질 않아 이슈 문의 드립니다. 확인 부탁 드립니다 ㅠ_ㅠ

**Comment by kimhamc** [comment]
http://heycrybaby.com/index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver

해당 페이지 URL 드립니다.

**Comment by YJSoft** [comment]
http://heycrybaby.com/index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver -> http://heycrybaby.com/index.php?module=loginxeclient&act=dispLoginxeclientOAuth&provider=naver

서버모듈 설정 매뉴얼 http://server.loginxe.cf/
