### ISSUE TITLE
LoginXE 설정상에 어려움이 있어 문의 드립니다.

### ISSUE THREAD

**Issue by choi6157** [YJSoft/xe-module-loginxeclient#13]
좋은 자료 감사드립니다. ^^ 설정상에 어려움이 있어 문의 드립니다.
우선 로그인XE 서버 아이디/키 ??? 란 LoginXE Server 에 맨 위에 임의생성된 로그인XE 클라이언트 아이디 / 로그인XE 클라이언트 Key를 의미하는것 같아 그대로 입력했지만 oops!페이지만 나오고 있습니다. 레이아웃은 xedition 로그인위젯에 네이버 버튼 추가방식으루 그대로 했구요... ※ 프로토콜 버전 1.0 업데이트가 필요합니다. 가 뜨는데 버전 때문인지요?

**Comment by YJSoft** [comment]
클라이언트 모듈과 서버 모듈을 모두 최신 베타버전으로 업데이트 해주세요.
그래도 오류가 발생한다면 오류 화면을 캡쳐해서 올려 주세요. (입력칸 아래 selecting them 클릭으로 첨부 가능합니다)

**Comment by YJSoft** [comment]
증상이 재현되지 않습니다.
베타버전 사용시에도 문제가 있다면 이슈를 다시 올려주세요.
