### ISSUE TITLE
'등록된 도메인이 아닙니다' 문제

### ISSUE THREAD

**Issue by aviatism** [YJSoft/xe-module-loginxeclient#14]
서버모듈과 클라이언트 모듈을 제공해주신 매뉴얼대로 설정 완료하였습니다.

회원페이지의 외부로그인 연결 메뉴에서 네이버 : 연결안됨 으로 되어있어서 그 '연결안됨'을 클릭하니 '등록된 도메인이 아닙니다' 라고 나옵니다.

이는 모듈설정상의 문제인가요, 네이버쪽의 문제인가요?

**Comment by YJSoft** [comment]
@aviatism 서버 모듈 설정에서 도메인을 추가해주세요
추가시 `http://`나 주소 맨 뒤 `/`를 빼셔야 합니다.

**Comment by aviatism** [comment]
물론 뺐습니다. 메뉴얼대로 설정 완벽하게 완료하였습니다.
