### ISSUE TITLE
도움 부탁드립니다... 로그인 xe 클라이언트 문의드려요,.

### ISSUE THREAD

**Issue by hihellomin** [YJSoft/xe-module-loginxeclient#15]
로그인 xe 서버는 알려주신 대로, 
작성하였습니다.

네아개발자도구에서 발급된 아이디와 키를 적고
콜백 주소를 네아에 적고,
로그인 사용 허가 도메인에  lllatt.com  을 적었습니다.

로그인 xe 서버 모듈에서 나온 클라이언트 아이디와 키를 

로그인 xe 클라이언트 모듈에 들어가 붙여넣기 하였습니다,

로그인 서버 xe 주소 에는 http://www.lllatt.com 

적어보았으나, 홈페이지 내에 별다른 작동이 없습니다.

말씀해주신대로

로그인XE 서버 주소 : 인증이 이루어지는 로그인 XE 서버 모듈이 설치된 주소입니다. 주소 뒤 /xe가 붙는다면 /xe까지 포함해야 하며 맨 뒤 슬래시는 붙이지 마세요. http://를 붙이셔야 합니다!
로그인XE 로그인 서비스 제공자 : 네이버/깃허브 중 사용할 로그인 방식을 선택할 수 있습니다. 체크하지 않은 방식은 사용할 수 없습니다.
로그인XE 서버 아이디/키 : 로그인 XE 서버 모듈에서 설정한 아이디와 Key값을 입력합니다.
이 값이 다를 경우 인증이 되지 않습니다.

1.04 버전 이후로 업데이트시 회원 페이지에 연동 메뉴가 생깁니다. <--- 연동메뉴..?

연동메뉴가 생기지 않습니다.

그래서 
http://www.lllatt.com/modules/loginxeserver
서버가 설치된 폴더명도 적어보고,

아닌가 해서 

http://lllatt.com/index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver

이것도 적어봣는데. 회원 페이지에 연동 메뉴가 생기지 않습니다.

그냥 전과 다른게 없습니다.

그래서 http://lllatt.com/index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver

이 주소를 쳐보니,  네이버아이디로 lllatt 사이트에 이용하는거 동의하냐고 묻는 네아 기능이 정상작동하는 것을 확인하였습니다.

서버는 제대로 들어간거 같은데

클라이언트 작동법을 모르겠습니다.  . . .

회원가입 버튼을 눌러봐도 네이버 아이디로 가입하기 이런것도 안나옵니다.. 당연히

뭔가 잘못된 거 같은데 모르겠습니다... 레이아웃을 제가 다른 곳에서 산걸 적용시켜서 그렇다기는 아닌것 같은데... 도와주세요.

**Comment by YJSoft** [comment]
@hihellomin 로그인 이후 메뉴가 생깁니다.
르그인전 로그인 버튼 추가 등은 https://www.xpressengine.com/tip/23002615 나 클라이언트 매뉴얼 등을 참고해서 직접 넣어주셔야 합니다.

**Comment by hihellomin** [comment]
좋은 모듈을 만들어 주셔서 감사합니다!

제가 바보라 이해를 잘 못해서 다시 질문 올려요!

로그인 이후 메뉴가 생긴다는 말씀이 , 어떤 로그인을 말씀하시는지 잘 모르겠습니다..ㅠ_ ㅠ 

1.Xe 관리자 모드 로그인
2.일반 가입 회원 로그인
3. 다른 로그인???

제가 이해했던건 관리자모드로 로그인을 하면 관리자 대쉬보드가 있고 옆에 XE 메뉴들이 있는데
그중 회원 탭에 있는 것에 밑에 무엇이 생길 줄 알았는데 생기지가 않아서요..

아 그리고 클라이언트에 로그인XE 서버 주소에는 그냥 대표주소를 적으면 되나요?
http://www.lllatt.com 

이런식으로요 아니면 http://www.lllatt.com/modules/loginxeserver
서버가 설치된 폴더명도 적어보고,
http://lllatt.com/index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver

이 3개 다 적어봤거든요..

친절하고 빠른 답변 감사합니다. 아마 고수시니까 제가 하는 내용들이 무척이나 답답하실 것 모두 알고 있습니다. ㅠ_ ㅠ 
그럼에도 불구하고 제가 너무 이 기능을 사용하고 싶어서 민폐임에도 불구하고 질문글을 올립니다.!

죄송합니다! 도와주세요!

**Comment by YJSoft** [comment]
@hihellomin 
![image](https://cloud.githubusercontent.com/assets/5893514/7964073/ed6a2a82-0a50-11e5-9e31-09a4387f2801.png)
