### ISSUE TITLE
네이버 아이디가 XE 아이디 규칙에 맞지 않는 경우 강제 수정

### ISSUE THREAD

**Issue by YJSoft** [YJSoft/xe-module-loginxeclient#7]

**Comment by 1bobby** [comment]
아직 숫자로 시작하는 네이버 아이디의 경우 로그인이 안되나 보네요.
아이디의 값은 영문, 숫자, _만 가능하며 첫 글자는 영문이어야 합니다.라고 나오네요..

**Comment by YJSoft** [comment]
@1bobby 이제 이슈 등록하고 작업 진행하려고 하니 조금만 기다려주세요 ^^;;;

**Comment by YJSoft** [comment]
fixed bdaac3f6087720bfd44259125ceee7a14e22f891
